Repository kubernetes-sigs/container-object-storage-interface-provisioner-sidecar, pull requests merged in 2020-12, with the labels that each got.

#3 Added grpc client and server modules
  go.mod
  go.sum
  pkg/grpcclient/client.go
  pkg/grpcserver/server.go
Labels: approved, cncf-cla: yes, lgtm, size/L

#15 updated README.md
  README.md
Labels: approved, cncf-cla: yes, lgtm, size/M

#10 Add BucketAccess Controller
  go.mod
  go.sum
  pkg/controller/bucketaccess/bucket_access_controller.go
  pkg/controller/bucketaccess/bucket_access_controller_test.go
Labels: approved, cncf-cla: yes, lgtm, size/XXL

#19 Fix make and make test
  .gitignore
  Makefile
  go.mod
  go.sum
  pkg/controller/bucketaccess/bucket_access_controller.go
Labels: approved, cncf-cla: yes, lgtm, size/L

#20 BucketAccess Controller fixes
  go.mod
  go.sum
  pkg/controller/bucketaccess/bucket_access_controller.go
  pkg/controller/bucketaccess/bucket_access_controller_test.go
Labels: approved, cncf-cla: yes, lgtm, size/M

#9 Added bucket controller
  pkg/controller/bucket/bucket_controller.go
  pkg/controller/bucket/bucket_controller_test.go
Labels: approved, cncf-cla: yes, lgtm, size/XL

#21 Added binary source and build target
  Makefile
  cmd/objectstorage-sidecar/app/objectstorage-sidecar.go
  cmd/objectstorage-sidecar/main.go
  go.mod
  go.sum
  pkg/controller/bucket/bucket_controller.go
  pkg/controller/bucketaccess/bucket_access_controller.go
Labels: approved, cncf-cla: yes, lgtm, size/L
