Repository kubernetes-sigs/container-object-storage-interface-provisioner-sidecar, pull requests merged in 2021-03, with the labels that each got.

#39 Update Spec+API versions
  .gitignore
  README.md
  cmd/objectstorage-sidecar/app/objectstorage-sidecar.go
  cmd/sample-driver/driver-server.go
  go.mod
  go.sum
  pkg/controller/bucket/bucket_controller.go
  pkg/controller/bucket/bucket_controller_test.go
  pkg/controller/bucketaccess/bucket_access_controller.go
  pkg/controller/bucketaccess/bucket_access_controller_test.go
  pkg/grpcserver/server.go
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/XL

#41 add identity server to sample-driver
  cmd/sample-driver/driver-server.go
  cmd/sample-driver/identity-server.go
  cmd/sample-driver/sample-driver.go
  pkg/grpcserver/server.go
Labels: approved, cncf-cla: yes, lgtm, size/M

#42 add minio.yaml for deploying sample driver
  minio.yaml
Labels: approved, cncf-cla: yes, lgtm, size/M

#40 Updated README.md
  README.md
Labels: approved, cncf-cla: yes, lgtm, needs-ok-to-test, size/M

#45 added image registry name and tag
  Makefile
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/XS

#37 Add Deployment documentation
  docs/deployment-guide.md
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/S

#47 added cloudbuiild.yaml
  cloudbuild.yaml
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/XS
