Repository kubernetes-sigs/container-object-storage-interface-provisioner-sidecar, pull requests merged in 2021-01, with the labels that each got.

#22 Added Dockerfile for sidecar
  Dockerfile
  cmd/objectstorage-sidecar/app/objectstorage-sidecar.go
Labels: approved, cncf-cla: yes, lgtm, size/XS

#24 added kustomize template & k8s resources for sidecar
  kustomization.yaml
  resources/deployment.yaml
  resources/ns.yaml
  resources/rbac.yaml
  resources/sa.yaml
  resources/secret.yaml
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/L

#25 Fix context definition
  cmd/objectstorage-sidecar/app/objectstorage-sidecar.go
Labels: approved, cncf-cla: yes, lgtm, size/XS

#26 fix sidecar image name
  resources/deployment.yaml
Labels: approved, cncf-cla: yes, lgtm, size/XS

#27 Add sample driver
  Dockerfile.sample-driver
  Makefile
  README.md
  cmd/objectstorage-sidecar/app/objectstorage-sidecar.go
  cmd/objectstorage-sidecar/main.go
  cmd/sample-driver/driver-server.go
  cmd/sample-driver/sample-driver.go
  go.mod
  go.sum
Labels: approved, cncf-cla: yes, lgtm, size/XL

#28 Remove log levels and use klog v2
  cmd/objectstorage-sidecar/app/objectstorage-sidecar.go
  cmd/sample-driver/driver-server.go
  cmd/sample-driver/sample-driver.go
  go.mod
  pkg/controller/bucket/bucket_controller.go
  pkg/controller/bucketaccess/bucket_access_controller.go
  pkg/grpcclient/client.go
  pkg/grpcserver/server.go
Labels: approved, cncf-cla: yes, lgtm, size/M

#29 Fix handling of nil parameters in B and BA
  pkg/controller/bucket/bucket_controller.go
  pkg/controller/bucket/bucket_controller_test.go
  pkg/controller/bucketaccess/bucket_access_controller.go
  pkg/controller/bucketaccess/bucket_access_controller_test.go
Labels: approved, cncf-cla: yes, lgtm, size/L

#31 Added Dockerfile to build sidecar as well as sample driver
  cmd/objectstorage-sidecar/Dockerfile
  cmd/sample-driver/Dockerfile
Labels: approved, cncf-cla: yes, lgtm, size/XS
