Repository kubernetes-sigs/container-object-storage-interface-provisioner-sidecar, pull requests merged in 2022-08, with the labels that each got.

#66 Added push to Cloudbuild.yaml and swapped out quay.io with gcr repo
  Makefile
  cloudbuild.yaml
Labels: ok-to-test, approved, cncf-cla: yes, lgtm, size/XS

#64 Updating code with KEP
  cmd/objectstorage-sidecar/cmd.go
  go.mod
  go.sum
  pkg/bucket/bucket_controller.go
  pkg/bucket/bucket_controller_test.go
  pkg/bucketaccess/bucketaccess_controller.go
  pkg/bucketaccess/bucketaccess_controller_test.go
  pkg/consts/consts.go
  pkg/provisioner/client.go
Labels: ok-to-test, approved, cncf-cla: yes, lgtm, size/XXL

#68 Fixing the pipeline to push build images
  cloudbuild.yaml
  go.mod
  go.sum
Labels: ok-to-test, approved, cncf-cla: yes, size/S, lgtm

#69 Create CHANGELOG-0.1.md
  CHANGELOG/CHANGELOG-0.1.md
Labels: approved, cncf-cla: yes, size/XS
