Repository kubernetes-sigs/container-object-storage-interface-provisioner-sidecar, pull requests merged in 2022-09, with the labels that each got.

#72 Update cloudbuild.yaml
  cloudbuild.yaml
Labels: approved, cncf-cla: yes, size/XS

#71 Update Makefile
  Makefile
Labels: approved, cncf-cla: yes, size/XS

#70 fix test file path in README.md
  README.md
Labels: ok-to-test, cncf-cla: yes, lgtm, size/XS

#73 Fix: Bucket and BucketAccess object updation facing stale object and improved logging
  pkg/bucket/bucket_controller.go
  pkg/bucketaccess/bucketaccess_controller.go
Labels: ok-to-test, approved, cncf-cla: yes, lgtm, size/L
